name: hugo publish

on:
  push:
    branches:
      - main

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
  
jobs:
  build-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: '0.80.0'

      - name: Build
        run: hugo --minify
        
      - name: Commit the generated website and push to git repository
        run: |
          git config --global user.email "team@pi4j.com"
          git config --global user.name "Pi4J Build"
          git checkout -b publish
          git fetch
          git add docs/.
          git commit -am "[AUTO] New version of website"
          git push origin HEAD:publish
          
